name: continuous integration & continuous deployment to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: akhileshns/heroku-deploy@v3.12.12
                with:
                    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                    heroku_app_name: "ae-resume-generator" #Must be unique in Heroku
                    heroku_email: "zipengliang21@gmail.com"